name: Merge to Main
on:
    push:
        branches: [main]

jobs:
    build:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        name: Bun Build
        steps:
            - uses: actions/checkout@v3
            - name: Run linting rules and tests
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest
            - run: bun install
            - run: buh run build
