name: Pull Request

on:
    pull_request:
        branches: [main]

jobs:
    build:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node: [14, 16, 18]

        name: Node ${{ matrix.node }} sample
        steps:
            - uses: actions/checkout@v3
            - name: Run linting rules and tests
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest
            - run: bun install
            - run: bun test
            - run: bun run build
