name: Pull Request

on:
    pull_request:
        branches: [main]

jobs:
    build:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        name: run tests on prs
        steps:
            - uses: actions/checkout@v3
            - name: Run tests
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest
            - run: bun install
            - run: bun test
            - run: bun run build
