name: Publish Package to npmjs
on:
    release:
        types: [created]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: install bun for tests and publish
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest
            - name: node publish
              uses: actions/setup-node@v4
              with:
                  node-version: '20.x'
                  registry-url: 'https://registry.npmjs.org'
            - run: bun install
            - run: bun test
            - run: bun run build
            - run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
